---
abstract: 'Parse text data formatted in space separated columns optionnaly on multiple lines'
author:
  - 'Olivier Mengue <dolmen@cpan.org>'
configure_requires:
  Module::Build: 0.36
  Test::More: 0
  Test::NoWarnings: 1.01
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-FixedLengthMultiline
provides:
  Text::FixedLengthMultiline:
    file: lib/Text/FixedLengthMultiline.pm
    version: 0.07
requires:
  Carp: 0
  constant: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-FixedLengthMultiline
  homepage: http://github.com/dolmen/Text-FixedLengthMultiline-perl
  repository: git://github.com/dolmen/Text-FixedLengthMultiline-perl.git
version: 0.07
